### ISSUE TITLE
Add macOS defaults script

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/dotfiles#25]
I've generally changed my defaults when I change computers manually, it
would be nice to have them happen automatically.

One that I like and can't find a GUI option for is to fade the hidden
applications in the Dock:

```
% defaults write com.apple.Dock showhidden -bool YES
```

**Comment by gabebw** [comment]
Here’s my (old) script for macOS settings: https://github.com/gabebw/dotfiles/blob/master/system/osx-settings

**Comment by teoljungberg** [comment]
Resolved by my migration from Homebrew to Nix as this is supported by Nix Darwin.

https://github.com/teoljungberg/dotfiles/commit/a825dcfa5aefb0ce5f30c81914df4521c7d87e1e
