### ISSUE TITLE
Rust language server

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/dotfiles#7]
I've been experimenting with Rust recently, and I'm trying to write all side projects or small programs in Rust to practice.

I find the language tricky to navigate, based on which methods I can call. Can a language server be used somehow?

**Comment by teoljungberg** [comment]
Or for that matter, any completion really.

**Comment by teoljungberg** [comment]
Can the documentation be viewed somehow? There is support for that in vim-racer somehow:

https://github.com/racer-rust/vim-racer/blob/cd663ddacc89fb3cbbb9649f7cd36528960b1fe9/autoload/racer.vim#L110

**Comment by Mange** [comment]
Yes, but you have to choose a binding manually it would seem. Check the ftplugin file to see how it is set up.

**Comment by teoljungberg** [comment]
@Mange Yeah, I do like that I can set my own mappings up!
