### ISSUE TITLE
Try out Ale

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/dotfiles#8]
Hide gutter, at all times. I only want the location- or quickfix-list to be used.

**Comment by gabebw** [comment]
I recommend these mappings to quickly move from one linting error to the next: https://github.com/gabebw/dotfiles/blob/3d2c55fcceea595f75e8bbc9d9ca6de176d9e704/vimrc#L299-L301

**Comment by teoljungberg** [comment]
@gabebw They look neat! Thanks.

Is there a way to hide the gutter in ale?

**Comment by teoljungberg** [comment]
@gabebw But, why not navigate the location list in itself rather than navigating ale? `:lnext` and `:lprev` are mapped as `]l` and `[l` respectively by vim-unimpaired.

**Comment by gabebw** [comment]
@teoljungberg Because despite your wonderful efforts, I still don't "get" the location list 😬

**Comment by teoljungberg** [comment]
@gabebw The easiest explanation I have is that’s a buffer specific quickfix list. Whete the quickfix list is global per tab.

**Comment by teoljungberg** [comment]
Whick makes it excellent for linting!
