### ISSUE TITLE
Global rubocop config

### ISSUE THREAD

**Issue by teoljungberg** [teoljungberg/dotfiles#9]
I'm quite opinionated about my ruby style, as some could guess.

I'm thinking that I should have a rubocop config in my dotfiles, but I wonder how that would work with a specific project doing something different than my config? Can they override eachother?

Is it possible for the project specific rubocop config to take precedence over the global one?

**Comment by Mange** [comment]
Good call. I too would want this.

Subscribing to this issue like the lazy bastard that I am. 😃

**Comment by gabebw** [comment]
Yes, local configurations take precedence over global configurations: `.rubocop` overrides `~/.rubocop`.

I have a global rubocop: https://github.com/gabebw/dotfiles/blob/master/rubocop.yml

**Comment by teoljungberg** [comment]
I've used https://github.com/testdouble/standard more and more, and that's enough until https://github.com/fables-tales/rubyfmt is more mainstream
